[pool]
mint = "EBm88rgvrZZeD2Rq1rEiXqT36VdK2ew1XYitn7Cji8Lc" # must be initialized beforehand
# pool-keypair = "./test-fixtures/example-pool-keypair.json" # defaults to randomly-generated if not specified
# validator-list-keypair = "./test-fixtures/example-validator-list-keypair.json" # defaults to randomly-generated if not specified
# reserve = "./test-fixtures/example-validator-list-keypair.json" # defaults to randomly-generated keypair if not specified

# manager = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to config wallet if not specified
# manager-fee-account = "4USVEavVayF32is9pz2oYWn6Vv77rTtMHUhvP5MBgXo2" # defaults to ATA of config wallet if not specified
# staker = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to config wallet if not specified

# deposit-auth = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to None if not specified
# sol-deposit-auth = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to None if not specified
# sol-withdraw-auth = "DAgQZufbVTGvJkDd3FhtcLPcmWXX7h5jzcePyVKCWZoL" # defaults to None if not specified

# preferred-deposit-validator = "BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2" # defaults to None if not specified
# preferred-withdraw-validator = "FnAPJkzf19s87sm24Qhv6bHZMZvZ43gjNUBRgjwXpD4v" # defaults to None if not specified

max-validators = 10
validators = [
    "BLADE1qNA1uNjRgER6DtUFf7FU3c1TWLLdpPeEcKatZ2",
    "FnAPJkzf19s87sm24Qhv6bHZMZvZ43gjNUBRgjwXpD4v",
]

stake-deposit-referral-fee = 50
sol-deposit-referral-fee = 0

[pool.epoch-fee]
denominator = 100
numerator = 6

[pool.stake-withdrawal-fee]
denominator = 1000
numerator = 1

[pool.sol-withdrawal-fee]
denominator = 1000
numerator = 1

[pool.stake-deposit-fee]
denominator = 0
numerator = 0

[pool.sol-deposit-fee]
denominator = 0
numerator = 0
